---
- name: Perform the essentials configuration
  hosts: all
  become: yes
  roles:
    - essentials

- name: Configure the monitoring applications
  hosts: all
  become: yes
  roles:
    - monitoring

- name: Configure the development applications
  hosts: all
  become: yes
  roles:
    - development

- name: Configure the storage services
  hosts: all
  become: yes
  roles:
    - storage
