---
- name: Perform the essentials configuration
  hosts: all
  become: yes
  roles:
    - essentials

- name: Configure the monitoring applications
  hosts: all
  become: yes
  roles:
    - monitoring
