---
- name: Update all installed packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Create /etc/prometheus directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: "0755"

- name: Create /var/lib/promethus directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: "0755"

- name: Download Prometheus 2.31.0
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.31.0/prometheus-2.31.0.linux-amd64.tar.gz
    dest: /var/tmp/prometheus-2.31.0.linux-amd64.tar.gz
    mode: "0440"

- name: Unarchive Prometheus 2.31.0
  ansible.builtin.unarchive:
    src: /var/tmp/prometheus-2.31.0.linux-amd64.tar.gz
    dest: /var/tmp
    remote_src: yes

- name: Move prometheus and promtool executable to /usr/local/bin
  command: mv /var/tmp/prometheus-2.31.0.linux-amd64/prometheus /var/tmp/prometheus-2.31.0.linux-amd64/promtool /usr/local/bin/

- name: Check /etc/prometheus/consoles/ directory
  stat:
    path: /etc/prometheus/consoles/
  register: consoles_folder_files_found

- name: Check /etc/prometheus/console_libraries/ directory
  stat:
    path: /etc/prometheus/console_libraries/
  register: console_libraries_folder_files_found

- name: Move consoles/ folder to /etc/prometheus/
  command: mv /var/tmp/prometheus-2.31.0.linux-amd64/consoles/ /etc/prometheus/
  when: consoles_folder_files_found.stat.exists == false

- name: Move console_libraries/ folder to /etc/prometheus/
  command: mv /var/tmp/prometheus-2.31.0.linux-amd64/console_libraries/ /etc/prometheus/
  when: console_libraries_folder_files_found.stat.exists == false

- name: Move configuration file to /etc/prometheus
  command: mv /var/tmp/prometheus-2.31.0.linux-amd64/prometheus.yml /etc/prometheus/prometheus.yml

- name: Copy prometheus.yml to /etc/prometheus
  ansible.builtin.copy:
    src: ./files/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Show prometheus version
  command: prometheus --version

- name: Ensure prometheus group exists
  ansible.builtin.group:
    name: prometheus
    state: present
    system: yes

# - name: Create prometheus user and assign it to the created prometheus group
#   command: sudo useradd -s /sbin/nologin --system -g prometheus prometheus

- name: Create /prometheus/ directory
  file:
    path: /prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0775

- name: Configure directory ownership and permissions
  command: sudo chown -R prometheus:prometheus /etc/prometheus /prometheus/

- name: Configure directory ownership and permissions
  command: sudo chown -R 775 /etc/prometheus/ /prometheus/

- name: Copy the Prometheus Service file
  ansible.builtin.copy:
    src: ./files/prometheus/prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus service
  ansible.builtin.systemd:
    state: started
    name: prometheus

- name: Enable Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    masked: no

- name: Open Firewall on Prometheus port (!this must be changed though. Only for testing purposes)
  command: sudo ufw allow 9090/tcp

- name: Reload Firewall service
  command: sudo ufw reload
